import type { Metadata } from "next";
import "./globals.css";
import { baiJamjuree, denkOne } from "../../fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${baiJamjuree.variable} ${denkOne.variable}`}>
      <body className={baiJamjuree.className}>{children}</body>
    </html>
  );
}
